Repository Daksh777/TakeABreak, pull requests merged in 2022-05, with the labels that each got.

#144 added pause and stop button
  index.html
  scripts/main.js
  styles/main.css
Labels: GSSoC22, Level2

#156 An update to Issue #52
  index.html
  scripts/main.js
  styles/main.css
Labels: GSSoC22, Level2

#160 updated localstorage for theme closes #138
  scripts/main.js
Labels: GSSoC22, Level1

#161 Improved circular timer's animation to smooth transition
  scripts/main.js
  styles/main.css
Labels: GSSoC22, Level1

#153 Adding logo
  assets/logo.svg
  index.html
  styles/IconFont.css
Labels: 7 days+

#165 Updated abbreviations for custom time input.
  scripts/main.js
Labels: GSSoC22, Level1

#166 Added an about section with the requested changes
  assets/about.svg
  index.html
  scripts/main.js
Labels: GSSoC22, Level1

#163 Colorful-theme Updated
  index.html
  scripts/main.js
  styles/colorful-theme.css
Labels: GSSoC22, Level1

#143 An API to fetch motivational quotes images
  index.html
  scripts/main.js
Labels: GSSoC22, Level1

#168 Fixed Buttons alignment + Removed Unnecessary codes
  styles/main.css
Labels: GSSoC22, Level1

#169 Favicons added to custom site cards
  scripts/main.js
Labels: GSSoC22, Level1
