Repository Daksh777/TakeABreak, pull requests merged in 2022-03, with the labels that each got.

#20 Added CONTRIBUTING.md file and CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: GSSoC22, Level1

#31 added check for empty url condition ( in Enter Website Directly input field )
  scripts/main.js
Labels: GSSoC22, Level1

#45 fixing git command
  CONTRIBUTING.md
Labels: GSSoC22, Level1

#36 Empty site link alert added and https prefix issue examined
  index.html
  scripts/main.js
Labels: GSSoC22, Level1

#72 Delete Icon updates, Confirm sweet alert added
  assets/delete.svg
  scripts/main.js
  styles/main.css
Labels: GSSoC22, Level1

#79 After changes
  assets/male50.mp3
  assets/male90.mp3
  assets/settings.svg
  index.html
  scripts/main.js
  styles/main.css
Labels: GSSoC22, Level3

#83 Remember settings state using local storage done
  index.html
  scripts/main.js
Labels: GSSoC22, Level2

#108 abbreviate it
  scripts/main.js
Labels: GSSoC22, Level1

#114 Update main.js
  scripts/main.js
Labels: GSSoC22, Level1

#119 added custom timer's valid numerical input checker
  scripts/main.js
Labels: GSSoC22, Level1
